# Generated by Django 3.1.7 on 2022-03-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisor', models.TextField()),
                ('orders', models.TextField()),
                ('completion', models.TextField()),
                ('price', models.TextField()),
                ('fiat', models.TextField()),
                ('payment', models.TextField()),
                ('available', models.TextField()),
                ('limit', models.TextField()),
            ],
        ),
    ]
