# Generated by Django 3.1.7 on 2022-03-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='advertisor_no',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='exchange',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
