# Generated by Django 3.1.7 on 2022-03-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20220330_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='advertisor',
            new_name='advertiser',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='advertisor_no',
            new_name='advertiser_no',
        ),
    ]
